diary/urls.py
from django.urls import path
from.import views

app_name = 'diary'

urlpatterns = [
    path('',views.index, name='index'),
    path('add/',views.add,name='add'),  #/dairy/add
    path('update/<int:pk>/',views.update,name='update'),
    path('delete/<int:pk>/',views.delete,name='delete'),
    path('detail/<int:pk>/',views.detail,name='detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/',include('diary.urls')),
]

diary/models.py
from django.db import models
from django.utils import timezone #djangoでは、datetimes.nowの変わりにtimezone.nowで現在日時時刻を取得する。

class Day(models.Model):
    title = models.CharField('タイトル',max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付',default=timezone.now)

    def __str__(self):
        return self.title

diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = '__all__' #('text','field','date)

diary/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import DayCreateForm
from .models import Day

def index(request):
    context={
        'day_list':Day.objects.all(),
    }
    return render(request,'diary/day_list.html',context)

def add(request):
    form = DayCreateForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context={
        'form':form
    }
    return render(request,'diary/day_form.html',context)


def update(request,pk):
    day = get_object_or_404(Day,pk=pk)
    form = DayCreateForm(request.POST or None,instance=day)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')
    context={
        'form':form
    }
    return render(request,'diary/day_form.html',context)


def delete(request,pk):
    day = get_object_or_404(Day,pk=pk)

    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')
    context={
        'day':day,
    }
    return render(request,'diary/day_confirm_delete.html',context)


def detail(request,pk):
    day = get_object_or_404(Day,pk=pk)

    context={
        'day':day,
    }
    return render(request,'diary/day_detail.html',context)

# Create your views here

diary/templates/diary/base.html
<!DOCTYPE html>
<html>
<head>
  <title>日記アプロケーション</title>
    <meta charset = "utf-8">

</head>
<body>
<nav class="nav">
  <a class="nav-link"href="{% url 'diary:index'%}">一覧</a>
  <a class="nav-link"href="{% url 'diary:add'%}">追加</a>
</nav>


{% block content %}
{% endblock %}
</body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    {{day.title}}
    {{day.text}}

    <button type="submit">送信</button>

    {% csrf_token %}

</form>
<P>こちらのページを削除します</P>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}
{% block content %}

<table class="table">
    <tr>
        <th>タイトル</th>
        <td>{{day.title}}</td>
    </tr>
    <tr>
        <th>内容</th>
        <td>{{day.text | linebreaksbr}}</td>
    </tr>
    <tr>
        <th>日付</th>
        <td>{{day.date}}</td>
    </tr>
</table>

{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="POST">
    {{form.as_p}}
    <button type="submit">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>
    日記帳アプリケーションです。
</h1>

<table>
    <thead>
    <tr>
        <th>タイトル</th>
        <th>内容</th>
        <th>日付</th>
        <th colspan="2"></th>
    </tr>
    </thead>
    <tbody>
    {% for day in day_list %}
    <tr>
        <td><a href="{% url 'diary:detail' day.pk %}" >{{day.title}}</a></td>
        <td>{{day.text}}</td>
        <td>{{day.date}}</td>
        <td><a href="{% url　'diary:update'　day.pk %}">更新</a></td>
        <td><a href="{% url　'diary:delete'　day.pk %}">削除</a></td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}